spring:
  datasource:
      driver-class-name: com.osisoft.jdbc.Driver
      url: jdbc:pioledb://localhost/Data Source=PIServer1; Integrated Security=SSPI
  mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
server:
  port: 8888
logging:
  level:
      root: debug